[font]
size = 6.5
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window.padding]
x = 10
y = 8

[general]
import = ["~/.config/alacritty/colors.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
