dofile(os.getenv("HOME") .. "/.config/conky/common.lua")

local x, y = position('disk')

conky.config = merge({
    gap_x = x,
    gap_y = y,
    own_window_title = 'conky-disk',
})

conky.text = [[
${color1}─── DISK ───────────────────────────${color}${voffset 12}
${color1}USED${color}  ${fs_used_perc /}%${alignr}${execpi 5 ~/.local/bin/conky-bar disk 13}${voffset 3}
${color3}${fs_used /} / ${fs_size /}${color}
]]
