dofile(os.getenv("HOME") .. "/.config/conky/common.lua")

local x, y = position('cpu')

conky.config = merge({
    gap_x = x,
    gap_y = y,
    own_window_title = 'conky-cpu',
    lua_draw_hook_post = 'draw_borders 87 72',
})

conky.text = [[
${color1}─── CPU ────────────────────────────${color}${voffset 12}
${color1}LOAD${color}  ${cpu cpu0}%${alignr}${execpi 2 ~/.local/bin/conky-bar cpu 13}${voffset 3}
${color1}TEMP${color}  ${execi 5 ~/.local/bin/cpu-temp}${voffset 10}
${offset 9}${top name 1}${alignr 9}${color3}${top cpu 1}%${color}${voffset 3}
${offset 9}${top name 2}${alignr 9}${color3}${top cpu 2}%${color}${voffset 3}
${offset 9}${top name 3}${alignr 9}${color3}${top cpu 3}%${color}${voffset 8}
]]
