dofile(os.getenv("HOME") .. "/.config/conky/common.lua")

local x, y = position('mail')

conky.config = merge({
    gap_x = x,
    gap_y = y,
    own_window_title = 'conky-mail',
})

conky.text = [[
${color1}─── MAIL ───────────────────────────${color}${voffset 12}
${color1}INBOX${color}  ${execi 5 awk 'NR==1' /tmp/imap-$USER.txt 2>/dev/null || echo -}${alignr}${execpi 5 ~/.local/bin/conky-mail-label}${voffset 3}
${color3}${execi 5 ~/.local/bin/conky-mail-subject}${color}
]]
