dofile(os.getenv("HOME") .. "/.config/conky/common.lua")

local x, y = position('mem')

conky.config = merge({
    gap_x = x,
    gap_y = y,
    own_window_title = 'conky-mem',
    lua_draw_hook_post = 'draw_borders 87 72',
})

conky.text = [[
${color1}─── MEMORY ─────────────────────────${color}${voffset 12}
${color1}USED${color}  ${memperc}%${alignr}${execpi 2 ~/.local/bin/conky-bar mem 13}${voffset 3}
${color3}${mem} / ${memmax}${color}${voffset 10}
${offset 9}${top_mem name 1}${alignr 9}${color3}${top_mem mem_res 1}${color}${voffset 3}
${offset 9}${top_mem name 2}${alignr 9}${color3}${top_mem mem_res 2}${color}${voffset 3}
${offset 9}${top_mem name 3}${alignr 9}${color3}${top_mem mem_res 3}${color}${voffset 8}
]]
